version: '3.8'
services:
  bot:
    build: .
    container_name: tashkent-cafe-bot
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./bot/data:/usr/src/app/data
    env_file:
      - ./bot/.env
