CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id BIGINT UNIQUE NOT NULL,
  name TEXT,
  username TEXT,
  last_order_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_uz TEXT NOT NULL,
  name_ko TEXT NOT NULL,
  price INTEGER NOT NULL,
  category TEXT NOT NULL,
  is_sold_out BOOLEAN DEFAULT FALSE,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  is_open BOOLEAN DEFAULT TRUE,
  closed_message TEXT DEFAULT 'Uzr, bugun dam olish kunimiz.',
  CONSTRAINT one_row CHECK (id = 1)
);

INSERT INTO settings (id, is_open, closed_message)
VALUES (1, TRUE, 'Uzr, bugun dam olish kunimiz.')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  mode TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  total INTEGER NOT NULL,
  payment_screenshot TEXT,
  ai_verified BOOLEAN,
  ai_amount BIGINT,
  ai_confidence REAL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id),
  menu_item_id BIGINT REFERENCES menu(id),
  name_uz TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price INTEGER NOT NULL
);

-- Boshlang'ich Menyuni kiritish
INSERT INTO menu (name_uz, name_ko, price, category) VALUES 
('Qozon kabob', '카잔 케밥', 12000, 'Ikkinchi taom'),
('Achiq go''sht', '매운 고기', 12000, 'Ikkinchi taom'),
('Sho''rva', '스프', 10000, 'Birinchi taom'),
('Xonim', '하눔', 10000, 'Ikkinchi taom'),
('Chuchvara', '만두', 9000, 'Birinchi taom'),
('Somsa (tovuqli)', '삼사 (닭고기)', 3000, 'Non & Pishiriq'),
('Somsa (go''shtli)', '삼사 (고기)', 4000, 'Non & Pishiriq'),
('Non kabob', '빵 케밥', 6000, 'Ikkinchi taom'),
('Lavash', '라바쉬', 6000, 'Ikkinchi taom'),
('Medoviy tort', '꿀 케이크', 6000, 'Non & Pishiriq'),
('Kremli tort', '크림 케이크', 7000, 'Non & Pishiriq'),
('Shokoladli tort', '초코 케이크', 7000, 'Non & Pishiriq')
ON CONFLICT DO NOTHING;
